//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETL_Rnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_etl_validation_TestProjectConnections
    {
        public int ID { get; set; }
        public int TestProjectID { get; set; }
        public string ConnectionType { get; set; }
        public string ServerType { get; set; }
        public string ServerIP { get; set; }
        public string TestDBName { get; set; }
        public string TestDBUserID { get; set; }
        public string TestPassword { get; set; }
        public int CreatedBy { get; set; }
        public string CreatedTimestamp { get; set; }
    }
}
