//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETL_Rnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_etl_validation_TestProjects
    {
        public int TestProjectID { get; set; }
        public string TestProjectName { get; set; }
        public string TestProjectDescription { get; set; }
        public string CreatedTimestamp { get; set; }
        public int CreatedBy { get; set; }
        public bool Status { get; set; }
    }
}
